#Drone CI File!
#Commit Message: Drone! Captain Canary is here! 

kind: pipeline
type: docker
name: default

steps:
  - name: build-image
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: run-script
    image: 915632791698.dkr.ecr.us-east-2.amazonaws.com/nginx-custom:latest
    commands:
      - ls -l

trigger:
  event:
    include:
    - push
    - pull_request
  branch:
    - master
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
